export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_IMAGES_PENDING = 'REQUEST_IMAGES_PENDING';
export const REQUEST_IMAGES_SUCCESS = 'REQUEST_IMAGES_SUCCESS';
export const REQUEST_IMAGES_FAILED = 'REQUEST_IMAGES_FAILED';